version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns: 
          - name: date_date
            description: date of the sale
          - name: orders_id
            description: identifier of an order
          - name: products_id
            description: identifier of a product
          - name: revenue
            description: how much did GZ get from the sales of that product
          - name: quantity
            description: the quantity of this product sold
        tests:
          - unique:
              column_name: "concat(orders_id,pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / a row represents a product_id and its purchase_price
        columns: 
          - name: products_id
            description: identifier of a product
            tests:
              - not_null
              - unique
          - name: purchase_price
            description: the price at which a product was purchased
      - name: ship
        identifier: raw_gz_ship
        description: each row represents the delivery costs of an order_id
        columns: 
          - name: orders_id
            description: identifier of an order
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: the cost charged for shipping a product to the customer
          - name: logcost
            description: the total cost associated with logistics operations
          - name: ship_cost
            description: the actual cost incurred by the company for shipping a product 
            
models:
  - name: int_orders_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: margin
        description: margin = revenue - purchase_cost
        tests:
          - not_null
      - name: Purchase_cost
        description: purchase_cost = quantity * purchase_price
        tests:
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: revenue
        description: sum of revenue per order
        tests:
          - not_null
      - name: quantity
        description: sum of quantity per order
        tests:
          - not_null

  - name: int_sales_margin
    description: margin calculation per order line / product sales
    columns:
    - name: orders_id
      description: orders key
      tests:
        - not_null
    - name: products_id
      description: products key
      tests:
           - not_null
    - name: margin
      description: margin = revenue - purchase_cost
      tests:
       - not_null
    - name: Purchase_cost
      description: purchase_cost = quantity * purchase_price
      tests:
        - not_null
    - name: date_date
      description: date of the order
      tests:
       - not_null
    - name: revenue
      description: sum of revenue per order
      tests:
       - not_null
    - name: quantity
      description: sum of quantity per order
      tests:
       - not_null
    tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"

  - name: int_orders_operational
    description: operational margin calculation per order
    columns:
    - name: orders_id
      description: primary key
      tests:
       - unique
       - not_null
    - name: date_date
      description: date of the order
      tests:
        - not_null
    - name: operational_margin
      description: operational_margin = margin + shipping_fee - logcost - ship_cost
    - name: quantity
      description: sum of quantity per order
      tests:
        - not_null
    - name: revenue
      description: sum of revenue per order
      tests:
        - not_null
    - name: purchase_cost
      description: purchase_cost = quantity * purchase_price
      tests:
        - not_null
    - name: margin
      description: margin = revenue - purchase_cost
      tests:
        - not_null
    - name: shipping_fee
      description: the price the customer pays for shipping
    - name: logcost
      description: the cost of preparing the parcel in the distribution centre/warehouse
    - name: ship_cost
      description: shipping cost paid by Greenweez to the carrier/logistics provider
